travis:
  secure:
    BINSTAR_TOKEN: NVuCPGYU9DRrTYxG2CQiAKJcZ1YOFeeOI3njPi8tPfNU4K/a9AcZpq6q7xUvDGRkGWloGf5vFXGvVYbKVfHXKf1FbnhmLP4S4L7BIH/WwMW43rS1fmqDvmylRsdyCvwvId8jOfvcz2+JhQuLA/L14B+70S/6OWl+9UJb1guFeiaYpAidi1819dSWsSvGss/T8FfVt47fh99RVi+Tm8fMar2kH3LqAjmEO4M+RqyE6JurlmnXdoZ+OgJggo/DO3zaRuNtaLm32wJjyJ0gZ4Empq0aI/qTqY2rJijygBKi7uXdpWJJH6nhpwlgzwRgDGRoHoWUYTcIp1s7WWFfadlHIPADazXADKSf4pvu/sOaWTfrSUBplr9PuyMCznryD9ZJ1WeNm/wNWhBpwHRVKMXahaX0qxySUIEj+Pod+9lz3f1Kc26nE1FGIGCC9eghHLa22hzmlqsx0zpxiI38inm10NuKpY1xMmB6Gf3WvaE02anpQNOQob0kwGNZj1lJqE+29vxuASdwOLSzh5QnmmsAiZA7gXrIZhLGpP4i7G8bRjGwfdVpTtJfx/gukVYPP0+8qJ9NIimCeSjKa/+UzUDkyDwjQq/ftJhFRpUwNgfeiWEDnPqpoGn3wpsc83VdA0grdGTnOcDG59lrm31DXkE99aZtpCUlVGJ/+IrJVVunP8c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
